### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by penglo** [HKUST-Aerial-Robotics/SIMPL#19]
Traceback (most recent call last):
File "train.py", line 182, in <module>
main()
File "train.py", line 102, in main
loss_out = loss_fn(out, data)
File "/root/miniconda/envs/simpl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/root/lanyun-tmp/Simpl/simpl/av2_loss_fn.py", line 29, in forward
cls, reg, aux = out
ValueError: not enough values to unpack (expected 3, got 2) 你好我在复现AV2代码时发现了这个问题i请问您遇到过吗

**Comment by MasterIzumi** [comment]
代码pull到最新了么？有做其他修改嘛？我这边测试当前版本是可以正常训练的。麻烦提供一下更多的细节~
